### ISSUE TITLE
Exception on launch - Value cannot be null

### ISSUE THREAD

**Issue by AxelHgt** [ZeroFox5866/nucleuscoop#26]
Hello !

At first, thank you ! That's seems amazing what you have done here !
However i have some problem to run Nucleus coop:

On launch:
```
System.ArgumentNullException: Value cannot be null.

   at System.Threading.Monitor.ReliableEnter(Object obj, Boolean& lockTaken)
   at Nucleus.Coop.MainForm.RefreshGames()
   at Nucleus.Coop.MainForm.OnShown(EventArgs e)
   at System.Windows.Forms.Form.CallShownEvent()
   at System.Windows.Forms.Control.InvokeMarshaledCallbackDo(ThreadMethodEntry tme)
   at System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Forms.Control.InvokeMarshaledCallback(ThreadMethodEntry tme)
   at System.Windows.Forms.Control.InvokeMarshaledCallbacks()
```

**System:**
Win 10  64-bit

**Comment by MathieuPlo** [comment]
I had the same problem but I managed to resolve it. Try to be sure that your antivirus software did not remove something in the nucleus coop directory and see if the error is still here.

**Comment by AxelHgt** [comment]
Thanks for your reply @MathieuPlo !
I already checked and unfortunately it's not from my antivirus

**Comment by AxelHgt** [comment]
OK found it, it seems that the required.NET Framework (4.7.2 or higher) do not want to be installed on my computer
