### ISSUE TITLE
Exception on script download - NullReferenceException

### ISSUE THREAD

**Issue by AxelHgt** [ZeroFox5866/nucleuscoop#27]
Hello !

Beside the error on launch (https://github.com/ZeroFox5866/nucleuscoop/issues/26#issue-804350937)

I encounter this error when i try to download a script:
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Nucleus.Coop.Forms.DownloadPrompt..ctor(Handler handler, MainForm mf, String zipFileName)
   at Nucleus.Coop.Forms.ScriptDownloader.btn_Download_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

**System:**
Win 10  64-bit

**Comment by AxelHgt** [comment]
OK found it, it seems that the required.NET Framework (4.7.2 or higher) do not want to be installed on my computer
